### PR TITLE
Revert "Revert "Update edits""

### PR DESCRIPTION
**Pull request by XDVelectical**
Reverts XDVelectical/Rank-set-up-staff#3

### CODE REVIEW

**Review by Velecticall — COMMENTED** [review]
Looks good

**Review by Velecticall — COMMENTED** [review]
Better

**Review by Velecticall — COMMENTED** [review]
Ok

**Review by Velecticall — COMMENTED** [review]
It looks much better now. Just add updates

**Review by XDVelectical — COMMENTED** [review]
done

**Review by Velecticall — COMMENTED** [review]
Done 

> looks good #4 ``

**Review by XDVelectical — COMMENTED** [review]
finished these

**Pull request merged**
